name: FishChecker
main: com.modcrafting.fishchecker.FishChecker
version: 0.1
website: http://modcrafting.com
author: Deathmarine
description: >
             Checking system for the FishBans website.
commands:
  fishcheck:
    description: Checks a player name against the FishBans website.
    usage: /<command> <player>
permissions:
  fishcheck.*:
    description: Allows the Administration to Full Control
    children:
      fishcheck.override: true
      fishcheck.command: true
      fishcheck.messages: true
  fishcheck.override:
    default: op
    description: Allows players to override the login check.
  fishcheck.command:
    default: op
    description: Allows players to use the /fishcheck command.
  fishcheck.messages:
    default: op
    description: Allows players to view login messages.