name: ${name}
main: ${groupId}.${artifactId}.${name}
version: ${version}
website: ${url}
author: Deathmarine
description: '${description}'
commands:
  fishcheck:
    description: Checks a player name against the FishBans website.
    permission: fishcheck.command
    usage: /<command> <player>
permissions:
  fishcheck.*:
    default: op
    description: Allows the Administration to Full Control
    children:
      fishcheck.override: true
      fishcheck.command: true
      fishcheck.messages: true
  fishcheck.override:
    description: Allows players to override the login check.
  fishcheck.command:
    description: Allows players to use the /fishcheck command.
  fishcheck.messages:
    description: Allows players to view login messages.
  fishcheck.alertself:
    default: false
    description: Allows players to view their own bans on login.