name: FishChecker
main: com.modcrafting.fishchecker.FishChecker
version: 0.8
website: http://fishbans.com
author: Deathmarine
description: >
             Checking system for the FishBans website.
commands:
  fishcheck:
    description: Checks a player name against the FishBans website.
    permission: fishcheck.command
    usage: /<command> <player>
permissions:
  fishcheck.*:
    default: op
    description: Allows the Administration to Full Control
    children:
      fishcheck.override: true
      fishcheck.command: true
      fishcheck.messages: true
  fishcheck.override:
    description: Allows players to override the login check.
  fishcheck.command:
    description: Allows players to use the /fishcheck command.
  fishcheck.messages:
    description: Allows players to view login messages.
  fishcheck.alertself:
    default: false
    description: Allows players to view their own bans on login.